title: Xuan Ouyang Homepage
page-top-title: Xuan Ouyang Homepage
profile-name: Xuan Ouyang
profile-position: Junior B.S. | University of Wisconsin-Madison | CS 2202
profile-edu: University of Wisconsin-Madison | Computer Science
profile-citations: Citations: 165 | h-index: 4
top-section-bg-text: A Dedicated NLP & ML System Nerd Dreaming of AGI World
about-subtitle: About Me
copyright-text: '&copy; Xuan Ouyang 2024. All Rights Reserved.'
